const data = [
    { name: "Technology" },
    { name: "Jokes" },
    { name: "Education" },
    { name: "Gaming" },
    { name: "News" },
    { name: "Music" },
    { name: "Movies" },
    { name: "Books" },
    { name: "Science" },
    { name: "Sports" },
    { name: "Memes" },
    { name: "Art" },
    { name: "Food" },
    { name: "Travel" },
    { name: "Fitness" },
    { name: "DIY" },
    { name: "Photography" },
    { name: "Ask Me Anything" },
    { name: "Politics" },
    { name: "History" },
    { name: "Finance" },
    { name: "Programming" },
    { name: "Health" },
    { name: "Fashion" },
    { name: "Parenting" },
    { name: "Space" },
    { name: "Anime" },
    { name: "Nature" },
    { name: "Relationships" },
    { name: "Pets" },
    { name: "Cryptocurrency" },
    { name: "Personal Finance" },
    { name: "Startups" },
    { name: "Investing" },
    { name: "Cars" },
    { name: "TV Shows" },
    { name: "Comics" },
    { name: "Humor" },
    { name: "Beauty" },
    { name: "Skincare" },
    { name: "Meditation" },
    { name: "Mindfulness" },
    { name: "Writing" },
    { name: "Poetry" },
    { name: "Gardening" },
    { name: "Home Improvement" },
    { name: "Interior Design" },
    { name: "Crafts" },
    { name: "Career" },
    { name: "Productivity" },
    { name: "Entrepreneurship" },
    { name: "Mental Health" },
    { name: "Vegan" },
    { name: "Keto" },
    { name: "Fantasy" },
    { name: "Horror" },
    { name: "Sustainability" },
    { name: "Minimalism" },
    { name: "Cooking" },
    { name: "Baking" },
    { name: "Photography" },
    { name: "Videography" },
    { name: "Marketing" },
    { name: "Freelancing" },
    { name: "Social Media" },
    { name: "UX/UI Design" },
    { name: "Web Development" },
    { name: "Blockchain" },
    { name: "Artificial Intelligence" },
    { name: "Virtual Reality" },
    { name: "Augmented Reality" },
    { name: "Robotics" },
    { name: "3D Printing" },
    { name: "eSports" },
    { name: "Language Learning" },
    { name: "Puzzles" },
    { name: "Board Games" },
    { name: "Card Games" },
    { name: "Travel Hacks" },
    { name: "Road Trips" },
    { name: "Urban Exploration" },
    { name: "Mythology" },
    { name: "Astronomy" },
    { name: "Geopolitics" },
    { name: "Sociology" },
    { name: "Anthropology" },
    { name: "Philosophy" },
    { name: "Ethics" },
    { name: "Legal Advice" },
    { name: "Real Estate" },
    { name: "Environmental Science" },
    { name: "Renewable Energy" },
    { name: "Wildlife" },
    { name: "Marine Biology" },
    { name: "Astrobiology" },
    { name: "Graphic Design" },
    { name: "Illustration" },
    { name: "Animation" },
    { name: "Theater" },
    { name: "Dance" }
]